api_platform:
  title: 'Core Service API'
  description: 'This API provides endpoints to manage core service data within a VilnaCRM.'
  version: '1.0.0'

  use_symfony_listeners: false

  openapi:
    overrideResponses: false

  defaults:
    extra_properties:
      rfc_7807_compliant_errors: true

  formats:
    jsonld: ['application/ld+json']

  error_formats:
    jsonproblem: ['application/problem+json']

  resource_class_directories:
    - '%kernel.project_dir%/src/Customer/Domain/Entity'
    - '%kernel.project_dir%/src/Internal/HealthCheck/Domain/ValueObject'
