api_platform:
  title: 'Core Service API'
  description: 'This API provides endpoints to manage core service data within a VilnaCRM.'
  version: '1.0.0'

  use_symfony_listeners: false

  openapi:
    overrideResponses: false

  defaults:
    pagination_partial: true
    paginationClientItemsPerPage: true
    extra_properties:
      rfc_7807_compliant_errors: true
      allow_extra_attributes: true
    collection:
      allow_extra_attributes: true
    stateless: true

  exception_to_status:
    ApiPlatform\Exception\FilterValidationException: 200

  formats:
    jsonld: ['application/ld+json']
    json: ['application/json']

  error_formats:
    jsonproblem: ['application/problem+json']

  resource_class_directories:
    - '%kernel.project_dir%/src/Core/Customer/Domain/Entity'
    - '%kernel.project_dir%/src/Internal/HealthCheck/Domain/ValueObject'

  mapping:
    paths:
      - '%kernel.project_dir%/config/api_platform/resources'
