doctrine_mongodb:
  connections:
    default:
      server: '%env(DB_URL)%'
      options: {}
  default_database: '%env(DB_NAME)%'
  document_managers:
    default:
      auto_mapping: true
      mappings:
        App:
          is_bundle: false
          dir: '%kernel.project_dir%/src/Shared/Domain/Document'
          prefix: 'App\Shared\Domain\Document'
          alias: App
