doctrine_mongodb:
  auto_generate_proxy_classes: true
  auto_generate_hydrator_classes: true
  types:
    ulid: 'App\Shared\Infrastructure\DoctrineType\UlidType'
  connections:
    default:
      server: '%env(DB_URL)%'
      options: {}
  document_managers:
    default:
      auto_mapping: true
      mappings:
        App:
          is_bundle: false
          type: xml
          dir: '%kernel.project_dir%/config/doctrine'
          prefix: 'App\Core\Customer\Domain\Entity'
          alias: App
