doctrine_mongodb:
  auto_generate_proxy_classes: true
  auto_generate_hydrator_classes: true
  connections:
    default:
      server: '%env(DB_URL)%'
      options: {}
  document_managers:
    default:
      auto_mapping: true
      mappings:
        App:
          is_bundle: false
          dir: '%kernel.project_dir%/src/Shared/Domain/Entity'
          prefix: 'App\Shared\Domain\Entity'
          alias: App
