# Development environment override
services:
  php:
    build:
      target: frankenphp_dev
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_DEBUG: ${APP_DEBUG:-1}
      FRANKENPHP_SITE_CONFIG: ${FRANKENPHP_SITE_CONFIG-hot_reload}
      FRANKENPHP_WORKER_CONFIG: ${FRANKENPHP_WORKER_CONFIG-watch}
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
    volumes:
      - ./:/srv/app
      - ./frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true

  structurizr:
    image: structurizr/lite:2024.07.02
    ports:
      - '${STRUCTURIZR_PORT}:8080'
    volumes:
      - ./:/usr/local/structurizr

  localstack:
    image: localstack/localstack:3.4.0
    ports:
      - '${LOCALSTACK_PORT}:4566'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -fsS http://localhost:4566/_localstack/health | grep -Eq "\"sqs\": \"(available|running)\""',
        ]
      interval: 5s
      timeout: 5s
      retries: 30
    environment:
      - SERVICES=sqs,ec2,s3,iam,sts
      - DEBUG=1
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  localstack_data:
