#!/usr/bin/env bash
set -euo pipefail

# Secure bootstrap for autonomous agent tooling in GitHub Codespaces.
# This script only uses environment variables and does not write secrets to repository files.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
SETTINGS_FILE="${ROOT_DIR}/.devcontainer/codespaces-settings.env"
# shellcheck source=scripts/codespaces/lib/github-auth.sh
. "${SCRIPT_DIR}/lib/github-auth.sh"

if [ -f "${SETTINGS_FILE}" ]; then
    # shellcheck disable=SC1090
    . "${SETTINGS_FILE}"
fi

readonly OPENCODE_CONFIG="${HOME}/.config/opencode/opencode.json"
readonly AGENT_ENV_DIR="${HOME}/.config/core-service"
readonly AGENT_SECRETS_FILE="${AGENT_ENV_DIR}/agent-secrets.env"
readonly AGENT_BASHRC_FILE="${HOME}/.bashrc"
readonly AGENT_BASHRC_START="# BEGIN CORE-SERVICE AGENT ENV"
readonly AGENT_BASHRC_END="# END CORE-SERVICE AGENT ENV"
: "${OPENCODE_MODEL:=openrouter/openai/gpt-5.2-codex}"
: "${OPENCODE_PROVIDER_BASE_URL:=https://openrouter.ai/api/v1}"
: "${OPENCODE_ENABLED_PROVIDERS:=openrouter}"
: "${OPENCODE_DEFAULT_AGENT:=build}"
: "${GH_HOST:=github.com}"
: "${GH_GIT_PROTOCOL:=ssh}"
: "${GH_PROMPT:=disabled}"

persist_agent_secrets_file() {
    local tmp_secrets_file
    tmp_secrets_file="$(mktemp)"

    {
        printf '# Generated by scripts/codespaces/setup-secure-agent-env.sh\n'
        printf 'export OPENROUTER_API_KEY=%q\n' "${OPENROUTER_API_KEY}"
        if [ -n "${GH_AUTOMATION_TOKEN:-}" ]; then
            printf 'export GH_AUTOMATION_TOKEN=%q\n' "${GH_AUTOMATION_TOKEN}"
        fi
    } > "${tmp_secrets_file}"

    mkdir -p "${AGENT_ENV_DIR}"
    chmod 700 "${AGENT_ENV_DIR}"
    chmod 600 "${tmp_secrets_file}"
    mv "${tmp_secrets_file}" "${AGENT_SECRETS_FILE}"
}

ensure_shell_sources_agent_secrets() {
    local tmp_bashrc
    tmp_bashrc="$(mktemp)"

    touch "${AGENT_BASHRC_FILE}"

    awk -v start="${AGENT_BASHRC_START}" -v end="${AGENT_BASHRC_END}" '
        $0 == start {skip=1; next}
        $0 == end {skip=0; next}
        skip == 0 {print}
    ' "${AGENT_BASHRC_FILE}" > "${tmp_bashrc}"

    cat >> "${tmp_bashrc}" <<'EOM'

# BEGIN CORE-SERVICE AGENT ENV
if [ -f "$HOME/.config/core-service/agent-secrets.env" ]; then
    . "$HOME/.config/core-service/agent-secrets.env"
fi
# END CORE-SERVICE AGENT ENV
EOM

    mv "${tmp_bashrc}" "${AGENT_BASHRC_FILE}"
}

build_enabled_providers_json() {
    jq -n --arg raw "${OPENCODE_ENABLED_PROVIDERS}" '
        $raw
        | split(",")
        | map(gsub("^[[:space:]]+|[[:space:]]+$"; ""))
        | map(select(length > 0))
    '
}

write_opencode_config() {
    local enabled_providers_json
    local tmp_config

    enabled_providers_json="$(build_enabled_providers_json)"
    tmp_config="$(mktemp)"

    jq -n \
        --arg schema "https://opencode.ai/config.json" \
        --arg model "${OPENCODE_MODEL}" \
        --arg default_agent "${OPENCODE_DEFAULT_AGENT}" \
        --arg api_key "{env:OPENROUTER_API_KEY}" \
        --arg base_url "${OPENCODE_PROVIDER_BASE_URL}" \
        --argjson enabled_providers "${enabled_providers_json}" '
        {
          "$schema": $schema,
          "model": $model,
          "provider": {
            "openrouter": {
              "options": (
                {
                  "apiKey": $api_key
                }
                + (
                    if ($base_url | length) > 0
                    then {"baseURL": $base_url}
                    else {}
                    end
                  )
              )
            }
          },
          "enabled_providers": $enabled_providers
        }
        + (
            if ($default_agent | length) > 0
            then {"default_agent": $default_agent}
            else {}
            end
          )
    ' > "${tmp_config}"

    mkdir -p "$(dirname "${OPENCODE_CONFIG}")"
    chmod 600 "${tmp_config}"
    mv "${tmp_config}" "${OPENCODE_CONFIG}"
}

cs_require_command gh
cs_require_command jq
cs_require_command opencode
cs_ensure_gh_auth

if [ -z "${OPENROUTER_API_KEY:-}" ]; then
    cat >&2 <<'EOM'
Error: OPENROUTER_API_KEY is not set.
Provide OPENROUTER_API_KEY as a Codespaces secret.
EOM
    exit 1
fi

persist_agent_secrets_file
ensure_shell_sources_agent_secrets
write_opencode_config

# Persist repository-defined GH defaults for CLI behavior in each fresh Codespace.
gh config set git_protocol "${GH_GIT_PROTOCOL}" --host "${GH_HOST}" >/dev/null 2>&1 || true
gh config set prompt "${GH_PROMPT}" >/dev/null 2>&1 || true

# Optional git identity from environment for autonomous commits.
if [ -n "${GIT_AUTHOR_NAME:-}" ]; then
    git config --global user.name "${GIT_AUTHOR_NAME}"
fi
if [ -n "${GIT_AUTHOR_EMAIL:-}" ]; then
    git config --global user.email "${GIT_AUTHOR_EMAIL}"
fi

echo "Secure agent environment is ready."
echo "GH auth: available (mode: ${CS_GH_AUTH_MODE:-unknown})."
echo "OpenCode configured:"
echo "  - model: ${OPENCODE_MODEL}"
echo "  - providers: ${OPENCODE_ENABLED_PROVIDERS}"
if [ -n "${OPENCODE_PROVIDER_BASE_URL}" ]; then
    echo "  - OpenRouter base URL: ${OPENCODE_PROVIDER_BASE_URL}"
fi
echo "Runtime secret env:"
echo "  - ${AGENT_SECRETS_FILE} (mode 600)"
echo "OpenCode config:"
echo "  - ${OPENCODE_CONFIG}"
