#!/usr/bin/env bash
set -euo pipefail

# Secure bootstrap for autonomous agent tooling in GitHub Codespaces.
# This script only uses environment variables and does not write secrets to repository files.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
SETTINGS_FILE="${ROOT_DIR}/.devcontainer/codespaces-settings.env"
# shellcheck source=scripts/codespaces/lib/github-auth.sh
. "${SCRIPT_DIR}/lib/github-auth.sh"

if [ -f "${SETTINGS_FILE}" ]; then
    # shellcheck disable=SC1090
    . "${SETTINGS_FILE}"
fi

readonly OPENCODE_CONFIG="${HOME}/.config/opencode/opencode.json"
readonly AGENT_ENV_DIR="${HOME}/.config/core-service"
readonly AGENT_SECRETS_FILE="${AGENT_ENV_DIR}/agent-secrets.env"
readonly AGENT_BASHRC_FILE="${HOME}/.bashrc"
readonly AGENT_BASHRC_START="# BEGIN CORE-SERVICE AGENT ENV"
readonly AGENT_BASHRC_END="# END CORE-SERVICE AGENT ENV"
: "${OPENCODE_MODEL:=openrouter/openai/gpt-5.2-codex}"
: "${OPENCODE_VARIANT:=xhigh}"
: "${OPENCODE_PROVIDER_BASE_URL:=https://openrouter.ai/api/v1}"
: "${OPENCODE_ENABLED_PROVIDERS:=openrouter}"
: "${OPENCODE_DEFAULT_AGENT:=build}"
: "${OPENCODE_PERMISSION:=allow}"
: "${GH_HOST:=github.com}"
: "${GH_GIT_PROTOCOL:=ssh}"
: "${GH_PROMPT:=disabled}"
: "${CODESPACE_GIT_IDENTITY_NAME:=opencode-bot}"
: "${CODESPACE_GIT_IDENTITY_EMAIL:=opencode-bot@users.noreply.github.com}"

TMP_FILES=()
CS_GIT_IDENTITY_NAME=""
CS_GIT_IDENTITY_EMAIL=""

cleanup_tmp_files() {
    local tmp_file
    for tmp_file in "${TMP_FILES[@]}"; do
        rm -f "${tmp_file}"
    done
}

track_tmp_file() {
    TMP_FILES+=("$1")
}

trap cleanup_tmp_files EXIT

persist_agent_secrets_file() {
    local tmp_secrets_file
    tmp_secrets_file="$(mktemp)"
    track_tmp_file "${tmp_secrets_file}"

    {
        printf '# Generated by scripts/codespaces/setup-secure-agent-env.sh\n'
        printf 'export OPENROUTER_API_KEY=%q\n' "${OPENROUTER_API_KEY}"
        if [ -n "${GH_AUTOMATION_TOKEN:-}" ]; then
            printf 'export GH_AUTOMATION_TOKEN=%q\n' "${GH_AUTOMATION_TOKEN}"
        fi
        if [ -n "${CS_GIT_IDENTITY_NAME:-}" ]; then
            printf 'export GIT_AUTHOR_NAME=%q\n' "${CS_GIT_IDENTITY_NAME}"
            printf 'export GIT_COMMITTER_NAME=%q\n' "${CS_GIT_IDENTITY_NAME}"
        fi
        if [ -n "${CS_GIT_IDENTITY_EMAIL:-}" ]; then
            printf 'export GIT_AUTHOR_EMAIL=%q\n' "${CS_GIT_IDENTITY_EMAIL}"
            printf 'export GIT_COMMITTER_EMAIL=%q\n' "${CS_GIT_IDENTITY_EMAIL}"
        fi
    } > "${tmp_secrets_file}"

    mkdir -p "${AGENT_ENV_DIR}"
    chmod 700 "${AGENT_ENV_DIR}"
    chmod 600 "${tmp_secrets_file}"
    mv "${tmp_secrets_file}" "${AGENT_SECRETS_FILE}"
}

ensure_shell_sources_agent_secrets() {
    local tmp_bashrc
    tmp_bashrc="$(mktemp)"
    track_tmp_file "${tmp_bashrc}"

    touch "${AGENT_BASHRC_FILE}"

    awk -v start="${AGENT_BASHRC_START}" -v end="${AGENT_BASHRC_END}" '
        $0 == start {skip=1; next}
        $0 == end {skip=0; next}
        skip == 0 {print}
    ' "${AGENT_BASHRC_FILE}" > "${tmp_bashrc}"

    cat >> "${tmp_bashrc}" <<'EOM'

# BEGIN CORE-SERVICE AGENT ENV
if [ -f "$HOME/.config/core-service/agent-secrets.env" ]; then
    . "$HOME/.config/core-service/agent-secrets.env"
fi
# END CORE-SERVICE AGENT ENV
EOM

    cat "${tmp_bashrc}" > "${AGENT_BASHRC_FILE}"
    rm -f "${tmp_bashrc}"
}

build_enabled_providers_json() {
    jq -n --arg raw "${OPENCODE_ENABLED_PROVIDERS}" '
        $raw
        | split(",")
        | map(gsub("^[[:space:]]+|[[:space:]]+$"; ""))
        | map(select(length > 0))
    '
}

write_opencode_config() {
    local enabled_providers_json
    local tmp_config

    enabled_providers_json="$(build_enabled_providers_json)"
    tmp_config="$(mktemp)"
    track_tmp_file "${tmp_config}"

    jq -n \
        --arg schema "https://opencode.ai/config.json" \
        --arg model "${OPENCODE_MODEL}" \
        --arg variant "${OPENCODE_VARIANT}" \
        --arg default_agent "${OPENCODE_DEFAULT_AGENT}" \
        --arg permission "${OPENCODE_PERMISSION}" \
        --arg api_key "{env:OPENROUTER_API_KEY}" \
        --arg base_url "${OPENCODE_PROVIDER_BASE_URL}" \
        --argjson enabled_providers "${enabled_providers_json}" '
        {
          "$schema": $schema,
          "model": $model,
          "permission": $permission,
          "provider": {
            "openrouter": {
              "options": (
                {
                  "apiKey": $api_key
                }
                + (
                    if ($base_url | length) > 0
                    then {"baseURL": $base_url}
                    else {}
                    end
                  )
              )
            }
          },
          "enabled_providers": $enabled_providers,
          "agent": {
            "build": {
              "model": $model,
              "variant": $variant,
              "permission": $permission
            }
          }
        }
        + (
            if ($default_agent | length) > 0
            then {"default_agent": $default_agent}
            else {}
            end
          )
    ' > "${tmp_config}"

    mkdir -p "$(dirname "${OPENCODE_CONFIG}")"
    chmod 600 "${tmp_config}"
    mv "${tmp_config}" "${OPENCODE_CONFIG}"
}

configure_git_identity() {
    local name email current_name current_email

    # Empty author/committer env vars override git config and break commits.
    if [ -z "${GIT_AUTHOR_NAME:-}" ]; then
        unset GIT_AUTHOR_NAME || true
    fi
    if [ -z "${GIT_AUTHOR_EMAIL:-}" ]; then
        unset GIT_AUTHOR_EMAIL || true
    fi
    if [ -z "${GIT_COMMITTER_NAME:-}" ]; then
        unset GIT_COMMITTER_NAME || true
    fi
    if [ -z "${GIT_COMMITTER_EMAIL:-}" ]; then
        unset GIT_COMMITTER_EMAIL || true
    fi

    current_name="$(git config --global --get user.name 2>/dev/null || true)"
    current_email="$(git config --global --get user.email 2>/dev/null || true)"

    name="${GIT_AUTHOR_NAME:-${current_name:-}}"
    email="${GIT_AUTHOR_EMAIL:-${current_email:-}}"

    if [ -z "${name}" ]; then
        name="${CODESPACE_GIT_IDENTITY_NAME}"
    fi
    if [ -z "${email}" ]; then
        email="${CODESPACE_GIT_IDENTITY_EMAIL}"
    fi

    git config --global user.name "${name}"
    git config --global user.email "${email}"

    # Keep author/committer identity explicit and non-empty in login shells.
    export GIT_AUTHOR_NAME="${name}"
    export GIT_AUTHOR_EMAIL="${email}"
    export GIT_COMMITTER_NAME="${name}"
    export GIT_COMMITTER_EMAIL="${email}"

    CS_GIT_IDENTITY_NAME="${name}"
    CS_GIT_IDENTITY_EMAIL="${email}"
}

cs_require_command gh
cs_require_command jq
cs_require_command opencode
cs_ensure_gh_auth

if [ -z "${OPENROUTER_API_KEY:-}" ]; then
    cat >&2 <<'EOM'
Error: OPENROUTER_API_KEY is not set.
Provide OPENROUTER_API_KEY as a Codespaces secret.
EOM
    exit 1
fi

configure_git_identity
persist_agent_secrets_file
ensure_shell_sources_agent_secrets
write_opencode_config

# Persist repository-defined GH defaults for CLI behavior in each fresh Codespace.
gh config set git_protocol "${GH_GIT_PROTOCOL}" --host "${GH_HOST}" >/dev/null 2>&1 || true
gh config set prompt "${GH_PROMPT}" >/dev/null 2>&1 || true

echo "Secure agent environment is ready."
echo "GH auth: available (mode: ${CS_GH_AUTH_MODE:-unknown})."
echo "Git identity configured:"
echo "  - name: ${CS_GIT_IDENTITY_NAME}"
echo "  - email: ${CS_GIT_IDENTITY_EMAIL}"
echo "OpenCode configured:"
echo "  - model: ${OPENCODE_MODEL}"
echo "  - variant: ${OPENCODE_VARIANT}"
echo "  - permission: ${OPENCODE_PERMISSION}"
echo "  - providers: ${OPENCODE_ENABLED_PROVIDERS}"
if [ -n "${OPENCODE_PROVIDER_BASE_URL}" ]; then
    echo "  - OpenRouter base URL: ${OPENCODE_PROVIDER_BASE_URL}"
fi
echo "Runtime secret env:"
echo "  - ${AGENT_SECRETS_FILE} (mode 600)"
echo "OpenCode config:"
echo "  - ${OPENCODE_CONFIG}"
