#!/usr/bin/env bash
set -euo pipefail

# Secure bootstrap for autonomous agent tooling in GitHub Codespaces.
# This script only uses environment variables and does not write secrets to repository files.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
SETTINGS_FILE="${ROOT_DIR}/.devcontainer/codespaces-settings.env"
# shellcheck source=scripts/codespaces/lib/github-auth.sh
. "${SCRIPT_DIR}/lib/github-auth.sh"

if [ -f "${SETTINGS_FILE}" ]; then
    # shellcheck disable=SC1090
    . "${SETTINGS_FILE}"
fi

readonly CODEX_CONFIG="${HOME}/.codex/config.toml"
readonly OPENROUTER_PROFILE_START="# BEGIN CORE-SERVICE OPENROUTER PROFILE"
readonly OPENROUTER_PROFILE_END="# END CORE-SERVICE OPENROUTER PROFILE"
readonly AGENT_ENV_DIR="${HOME}/.config/core-service"
readonly AGENT_SECRETS_FILE="${AGENT_ENV_DIR}/agent-secrets.env"
readonly AGENT_BASHRC_FILE="${HOME}/.bashrc"
readonly AGENT_BASHRC_START="# BEGIN CORE-SERVICE AGENT ENV"
readonly AGENT_BASHRC_END="# END CORE-SERVICE AGENT ENV"
: "${CODEX_DEFAULT_PROFILE:=openrouter}"
: "${CODEX_MODEL:=openai/gpt-5.2-codex}"
: "${CODEX_MODEL_PROVIDER:=openrouter}"
: "${CODEX_REASONING_EFFORT:=xhigh}"
: "${CODEX_REASONING_SUMMARY:=none}"
: "${CODEX_APPROVAL_POLICY:=never}"
: "${CODEX_SANDBOX_MODE:=danger-full-access}"
: "${CODEX_PROVIDER_NAME:=OpenRouter}"
: "${CODEX_PROVIDER_WIRE_API:=responses}"
: "${CODEX_PROVIDER_BASE_URL:=https://openrouter.ai/api/v1}"
: "${GH_HOST:=github.com}"
: "${GH_GIT_PROTOCOL:=ssh}"
: "${GH_PROMPT:=disabled}"

persist_agent_secrets_file() {
    local tmp_secrets_file
    tmp_secrets_file="$(mktemp)"

    {
        printf '# Generated by scripts/codespaces/setup-secure-agent-env.sh\n'
        printf 'export OPENROUTER_API_KEY=%q\n' "${OPENROUTER_API_KEY}"
        if [ -n "${GH_AUTOMATION_TOKEN:-}" ]; then
            printf 'export GH_AUTOMATION_TOKEN=%q\n' "${GH_AUTOMATION_TOKEN}"
        fi
    } > "${tmp_secrets_file}"

    mkdir -p "${AGENT_ENV_DIR}"
    chmod 700 "${AGENT_ENV_DIR}"
    chmod 600 "${tmp_secrets_file}"
    mv "${tmp_secrets_file}" "${AGENT_SECRETS_FILE}"
}

ensure_shell_sources_agent_secrets() {
    local tmp_bashrc
    tmp_bashrc="$(mktemp)"

    touch "${AGENT_BASHRC_FILE}"

    awk -v start="${AGENT_BASHRC_START}" -v end="${AGENT_BASHRC_END}" '
        $0 == start {skip=1; next}
        $0 == end {skip=0; next}
        skip == 0 {print}
    ' "${AGENT_BASHRC_FILE}" > "${tmp_bashrc}"

    cat >> "${tmp_bashrc}" <<'EOM'

# BEGIN CORE-SERVICE AGENT ENV
if [ -f "$HOME/.config/core-service/agent-secrets.env" ]; then
    . "$HOME/.config/core-service/agent-secrets.env"
fi
# END CORE-SERVICE AGENT ENV
EOM

    mv "${tmp_bashrc}" "${AGENT_BASHRC_FILE}"
}

# Trust model: full-access autonomous mode is expected only for ephemeral Codespaces.
# Outside Codespaces, require explicit opt-in to keep dangerous settings.
if [ "${CODEX_APPROVAL_POLICY}" = "never" ] \
    && [ "${CODEX_SANDBOX_MODE}" = "danger-full-access" ] \
    && [ "${CODESPACES:-}" != "true" ] \
    && [ "${ENABLE_DANGEROUS_AGENT:-}" != "true" ]; then
    echo "Warning: refusing danger-full-access outside Codespaces without ENABLE_DANGEROUS_AGENT=true." >&2
    CODEX_APPROVAL_POLICY="on-request"
    CODEX_SANDBOX_MODE="workspace-write"
fi

cs_require_command gh
cs_require_command codex
cs_ensure_gh_auth

if [ -z "${OPENROUTER_API_KEY:-}" ]; then
    cat >&2 <<'EOM'
Error: OPENROUTER_API_KEY is not set.
Provide OPENROUTER_API_KEY as a Codespaces secret.
EOM
    exit 1
fi

persist_agent_secrets_file
ensure_shell_sources_agent_secrets

default_profile="${CODEX_DEFAULT_PROFILE}"

mkdir -p "$(dirname "${CODEX_CONFIG}")"
touch "${CODEX_CONFIG}"

tmp_without_block=""
tmp_with_profile=""

validate_toml_scalar_env() {
    local var_name="$1"
    local var_value="$2"

    case "${var_value}" in
        *$'\n'*|*$'\r'*|*\"*|*\\*)
            echo "Error: ${var_name} contains unsupported characters for TOML scalar interpolation." >&2
            echo "Use a value without newlines, double quotes, or backslashes." >&2
            exit 1
            ;;
    esac
}

cleanup() {
    [ -n "${tmp_without_block}" ] && rm -f "${tmp_without_block}"
    [ -n "${tmp_with_profile}" ] && rm -f "${tmp_with_profile}"
}
trap cleanup EXIT

tmp_without_block="$(mktemp)"
tmp_with_profile="$(mktemp)"

# Remove previously managed OpenRouter block if present.
awk -v start="${OPENROUTER_PROFILE_START}" -v end="${OPENROUTER_PROFILE_END}" '
    $0 == start {skip=1; next}
    $0 == end {skip=0; next}
    skip == 0 {print}
' "${CODEX_CONFIG}" > "${tmp_without_block}"

# Force a single top-level profile key before the first TOML table.
awk -v profile="${default_profile}" '
BEGIN {inserted = 0}
/^[[:space:]]*profile[[:space:]]*=/ {next}
/^[[:space:]]*\[/ {
    if (inserted == 0) {
        print "profile = \"" profile "\""
        print ""
        inserted = 1
    }
}
{print}
END {
    if (inserted == 0) {
        if (NR > 0) {
            print ""
        }
        print "profile = \"" profile "\""
    }
}
' "${tmp_without_block}" > "${tmp_with_profile}"

for toml_env in \
    CODEX_MODEL \
    CODEX_MODEL_PROVIDER \
    CODEX_REASONING_EFFORT \
    CODEX_REASONING_SUMMARY \
    CODEX_APPROVAL_POLICY \
    CODEX_SANDBOX_MODE \
    CODEX_PROVIDER_NAME \
    CODEX_PROVIDER_WIRE_API \
    CODEX_PROVIDER_BASE_URL; do
    validate_toml_scalar_env "${toml_env}" "${!toml_env}"
done

cat >> "${tmp_with_profile}" <<EOM

# BEGIN CORE-SERVICE OPENROUTER PROFILE
[profiles.openrouter]
model = "${CODEX_MODEL}"
model_provider = "${CODEX_MODEL_PROVIDER}"
model_reasoning_effort = "${CODEX_REASONING_EFFORT}"
model_reasoning_summary = "${CODEX_REASONING_SUMMARY}"
# WARNING: this profile can execute shell commands without approval.
# It is intended for trusted, ephemeral GitHub Codespaces automation only.
approval_policy = "${CODEX_APPROVAL_POLICY}"
sandbox_mode = "${CODEX_SANDBOX_MODE}"

[model_providers.openrouter]
name = "${CODEX_PROVIDER_NAME}"
base_url = "${CODEX_PROVIDER_BASE_URL}"
env_key = "OPENROUTER_API_KEY"
wire_api = "${CODEX_PROVIDER_WIRE_API}"
# END CORE-SERVICE OPENROUTER PROFILE
EOM

mv "${tmp_with_profile}" "${CODEX_CONFIG}"

# Persist repository-defined GH defaults for CLI behavior in each fresh Codespace.
gh config set git_protocol "${GH_GIT_PROTOCOL}" --host "${GH_HOST}" >/dev/null 2>&1 || true
gh config set prompt "${GH_PROMPT}" >/dev/null 2>&1 || true

# Optional git identity from environment for autonomous commits.
if [ -n "${GIT_AUTHOR_NAME:-}" ]; then
    git config --global user.name "${GIT_AUTHOR_NAME}"
fi
if [ -n "${GIT_AUTHOR_EMAIL:-}" ]; then
    git config --global user.email "${GIT_AUTHOR_EMAIL}"
fi

echo "Secure agent environment is ready."
echo "GH auth: available (mode: ${CS_GH_AUTH_MODE:-unknown})."
echo "Codex profile configured:"
echo "  - ${default_profile}: model ${CODEX_MODEL} via ${CODEX_PROVIDER_NAME}"
echo "    reasoning: ${CODEX_REASONING_EFFORT}, summaries: ${CODEX_REASONING_SUMMARY}, approvals: ${CODEX_APPROVAL_POLICY}, sandbox: ${CODEX_SANDBOX_MODE}"
echo "    transport: direct OpenRouter API at ${CODEX_PROVIDER_BASE_URL}"
echo "Runtime secret env:"
echo "  - ${AGENT_SECRETS_FILE} (mode 600)"
echo "Default profile: ${default_profile}"
