openapi: 3.1.0
info:
  title: 'Core Service API'
  description: 'This API provides endpoints to manage core service data within a VilnaCRM.'
  version: 1.0.0
servers:
  -
    url: /
    description: ''
paths:
  /api/health:
    get:
      operationId: api_health_get
      tags:
        - HealthCheck
      responses:
        '204':
          description: 'Health check passed with no content to return.'
        '500':
          description: 'Health check failed.'
      summary: 'Retrieves a HealthCheck resource.'
      description: 'Retrieves a HealthCheck resource.'
      parameters: []
      deprecated: false
components:
  schemas:
    HealthCheck:
      type: object
      description: ''
      deprecated: false
      required:
        - initials
        - email
        - phone
        - leadSource
        - type
        - status
      properties:
        initials:
          maxLength: 255
          type:
            - string
            - 'null'
        email:
          format: email
          maxLength: 255
          externalDocs:
            url: 'https://schema.org/email'
          type:
            - string
            - 'null'
        phone:
          maxLength: 255
          type:
            - string
            - 'null'
        leadSource:
          maxLength: 255
          type:
            - string
            - 'null'
        type:
          type:
            - string
            - 'null'
        status:
          type:
            - string
            - 'null'
        confirmed:
          type:
            - boolean
            - 'null'
    Customer.CustomerPatch:
      type: object
      description: ''
      deprecated: false
      properties:
        initials:
          maxLength: 255
          type:
            - string
            - 'null'
        email:
          format: email
          maxLength: 255
          externalDocs:
            url: 'https://schema.org/email'
          type:
            - string
            - 'null'
        phone:
          maxLength: 255
          type:
            - string
            - 'null'
        leadSource:
          maxLength: 255
          type:
            - string
            - 'null'
        type:
          type:
            - string
            - 'null'
        status:
          type:
            - string
            - 'null'
        confirmed:
          type:
            - boolean
            - 'null'
    Customer.CustomerPut.jsonld:
      type: object
      description: ''
      deprecated: false
      required:
        - initials
        - email
        - phone
        - leadSource
        - type
        - status
      properties:
        initials:
          maxLength: 255
          type:
            - string
            - 'null'
        email:
          format: email
          maxLength: 255
          externalDocs:
            url: 'https://schema.org/email'
          type:
            - string
            - 'null'
        phone:
          maxLength: 255
          type:
            - string
            - 'null'
        leadSource:
          maxLength: 255
          type:
            - string
            - 'null'
        type:
          type:
            - string
            - 'null'
        status:
          type:
            - string
            - 'null'
        confirmed:
          type:
            - boolean
            - 'null'
    Customer.jsonld:
      type: object
      description: ''
      deprecated: false
      properties:
        '@context':
          readOnly: true
          oneOf:
            -
              type: string
            -
              type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum: ['http://www.w3.org/ns/hydra/core#']
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
        initials:
          type: string
        email:
          type: string
        phone:
          type: string
        leadSource:
          type: string
        type:
          type: string
          format: iri-reference
          example: 'https://example.com/'
        status:
          type: string
          format: iri-reference
          example: 'https://example.com/'
        confirmed:
          type: boolean
        ulid:
          $ref: '#/components/schemas/UlidInterface.jsonld'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    CustomerStatus.StatusCreate.jsonld:
      type: object
      description: ''
      deprecated: false
      required:
        - value
      properties:
        value:
          maxLength: 255
          type:
            - string
            - 'null'
    CustomerStatus.StatusPatch:
      type: object
      description: ''
      deprecated: false
      properties:
        value:
          maxLength: 255
          type:
            - string
            - 'null'
    CustomerStatus.StatusPut.jsonld:
      type: object
      description: ''
      deprecated: false
      required:
        - value
      properties:
        value:
          maxLength: 255
          type:
            - string
            - 'null'
    CustomerStatus.jsonld:
      type: object
      description: ''
      deprecated: false
      properties:
        '@context':
          readOnly: true
          oneOf:
            -
              type: string
            -
              type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum: ['http://www.w3.org/ns/hydra/core#']
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
        value:
          type: string
        ulid:
          type: string
    CustomerType.TypeCreate.jsonld:
      type: object
      description: ''
      deprecated: false
      required:
        - value
      properties:
        value:
          maxLength: 255
          type:
            - string
            - 'null'
    CustomerType.TypePatch:
      type: object
      description: ''
      deprecated: false
      properties:
        value:
          maxLength: 255
          type:
            - string
            - 'null'
    CustomerType.TypePut.jsonld:
      type: object
      description: ''
      deprecated: false
      required:
        - value
      properties:
        value:
          maxLength: 255
          type:
            - string
            - 'null'
    CustomerType.jsonld-output:
      type: object
      description: ''
      deprecated: false
      properties:
        '@context':
          readOnly: true
          oneOf:
            -
              type: string
            -
              type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum: ['http://www.w3.org/ns/hydra/core#']
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
        value:
          type: string
        ulid:
          $ref: '#/components/schemas/UlidInterface.jsonld-output'
    Error:
      type: object
      description: 'A representation of common errors.'
      deprecated: false
      properties:
        title:
          readOnly: true
          description: 'A short, human-readable summary of the problem.'
          type:
            - string
            - 'null'
        detail:
          readOnly: true
          description: 'A human-readable explanation specific to this occurrence of the problem.'
          type:
            - string
            - 'null'
        status:
          type: number
          example: 404
          default: 400
        instance:
          readOnly: true
          description: 'A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.'
          type:
            - string
            - 'null'
        type:
          readOnly: true
          description: 'A URI reference that identifies the problem type'
          type: string
    HealthCheck.jsonld:
      type: object
      description: ''
      deprecated: false
      properties:
        '@context':
          readOnly: true
          oneOf:
            -
              type: string
            -
              type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum: ['http://www.w3.org/ns/hydra/core#']
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
    UlidInterface.jsonld:
      type: object
      description: ''
      deprecated: false
      properties:
        '@context':
          readOnly: true
          oneOf:
            -
              type: string
            -
              type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum: ['http://www.w3.org/ns/hydra/core#']
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
    UlidInterface.jsonld-output:
      type: object
      description: ''
      deprecated: false
      properties:
        '@context':
          readOnly: true
          oneOf:
            -
              type: string
            -
              type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum: ['http://www.w3.org/ns/hydra/core#']
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
  responses: {  }
  parameters: {  }
  examples: {  }
  requestBodies: {  }
  headers: {  }
  securitySchemes: {  }
security: []
tags: []
webhooks: {  }
