openapi: 3.1.0
info:
  title: 'Core Service API'
  description: 'This API provides endpoints to manage core service data within a VilnaCRM.'
  version: 1.0.0
servers:
  -
    url: /
    description: ''
paths:
  /api/health:
    get:
      operationId: api_health_get
      tags:
        - HealthCheck
      responses:
        '204':
          description: 'Health check passed with no content to return.'
        '500':
          description: 'Health check failed.'
      summary: 'Retrieves a HealthCheck resource.'
      description: 'Retrieves a HealthCheck resource.'
      parameters: []
      deprecated: false
components:
  schemas:
    HealthCheck:
      type: object
      description: ''
      deprecated: false
  responses: {  }
  parameters: {  }
  examples: {  }
  requestBodies: {  }
  headers: {  }
  securitySchemes: {  }
security: []
tags: []
webhooks: {  }
