App\Customer\Domain\Entity\Customer:
  attributes:
    id:
      groups: ['output']
    email:
      groups: ['output', 'input']
    initials:
      groups: ['output', 'input']
    confirmed:
      groups: ['output', 'input']
    leadSource:
      groups: ['output', 'input']
    type:
      groups: ['output', 'input']
    status:
      groups: ['output', 'input']
    createdAt:
      groups: ['output']
    updatedAt:
      groups: ['output']
