App\Customer\Application\DTO\CustomerCreate:
  properties:
    initials:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255
      - App\Shared\Application\Validator\Initials: ~
    email:
      - NotBlank: { message: 'not.blank' }
      - Email: { message: 'email.invalid' }
      - Length:
          max: 255
      - App\Shared\Application\Validator\UniqueEmail: ~
    phone:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255
    leadSource:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255
    type:
      - NotBlank: { message: 'not.blank' }
    status:
      - NotBlank: { message: 'not.blank' }
    confirmed:
      - Type: { type: 'bool', message: 'This value should be a boolean.' }

App\Customer\Application\DTO\CustomerPatch:
  properties:
    initials:
      - Length:
          max: 255
      - App\Shared\Application\Validator\Initials:
    email:
      - Email: { message: 'email.invalid' }
      - Length:
          max: 255
      - App\Shared\Application\Validator\UniqueEmail: ~
    phone:
      - Length:
          max: 255
    leadSource:
      - Length:
          max: 255
    confirmed:
      - Type:
          type: 'bool'
          message: 'This value should be a boolean.'

App\Customer\Application\DTO\CustomerPut:
  properties:
    initials:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255
      - App\Shared\Application\Validator\Initials: ~
    email:
      - NotBlank: { message: 'not.blank' }
      - Email: { message: 'email.invalid' }
      - Length:
          max: 255
      - App\Shared\Application\Validator\UniqueEmail: ~
    phone:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255
    leadSource:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255
    type:
      - NotBlank: { message: 'not.blank' }
    status:
      - NotBlank: { message: 'not.blank' }
    confirmed:
      - Type:
          type: 'bool'
          message: 'This value should be a boolean.'

App\Customer\Application\DTO\TypePatch:
  properties:
    value:
      - Length:
          max: 255

App\Customer\Application\DTO\TypePut:
  properties:
    value:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255

App\Customer\Application\DTO\TypeCreate:
  properties:
    value:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255

App\Customer\Application\DTO\StatusCreate:
  properties:
    value:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255

App\Customer\Application\DTO\StatusPatch:
  properties:
    value:
      - Length:
          max: 255

App\Customer\Application\DTO\StatusPut:
  properties:
    value:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255
