App\Customer\Application\DTO\CustomerCreateDto:
  properties:
    initials:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255
      - App\Shared\Application\Validator\Initials: ~
    email:
      - NotBlank: { message: 'not.blank' }
      - Email: { message: 'email.invalid' }
      - Length:
          max: 255
      - App\Shared\Application\Validator\UniqueEmail: ~
    phone:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255
    leadSource:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255
    type:
      - NotBlank: { message: 'not.blank' }
    status:
      - NotBlank: { message: 'not.blank' }
    confirmed:
      - Type: { type: 'bool', message: 'This value should be a boolean.' }

App\Customer\Application\DTO\CustomerPatchDto:
  properties:
    initials:
      - Length:
          max: 255
      - App\Shared\Application\Validator\Initials:
    email:
      - Email: { message: 'email.invalid' }
      - Length:
          max: 255
      - App\Shared\Application\Validator\UniqueEmail: ~
    phone:
      - Length:
          max: 255
    leadSource:
      - Length:
          max: 255
    confirmed:
      - Type:
          type: 'bool'
          message: 'This value should be a boolean.'

App\Customer\Application\DTO\CustomerPutDto:
  properties:
    initials:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255
      - App\Shared\Application\Validator\Initials: ~
    email:
      - NotBlank: { message: 'not.blank' }
      - Email: { message: 'email.invalid' }
      - Length:
          max: 255
      - App\Shared\Application\Validator\UniqueEmail: ~
    phone:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255
    leadSource:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255
    type:
      - NotBlank: { message: 'not.blank' }
    status:
      - NotBlank: { message: 'not.blank' }
    confirmed:
      - Type:
          type: 'bool'
          message: 'This value should be a boolean.'

App\Customer\Application\DTO\TypePatchDto:
  properties:
    value:
      - Length:
          max: 255

App\Customer\Application\DTO\TypePutDto:
  properties:
    value:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255

App\Customer\Application\DTO\TypeCreateDto:
  properties:
    value:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255

App\Customer\Application\DTO\StatusCreateDto:
  properties:
    value:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255

App\Customer\Application\DTO\StatusPatchDto:
  properties:
    value:
      - Length:
          max: 255

App\Customer\Application\DTO\StatusPutDto:
  properties:
    value:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255
