
App\Customer\Application\DTO\CustomerCreateDto:
  properties:
    initials:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255
      - App\Shared\Application\Validator\Initials: ~
    email:
      - NotBlank: { message: 'not.blank' }
      - Email: { message: 'email.invalid' }
      - Length:
          max: 255
      - App\Shared\Application\Validator\UniqueEmail: ~
    phone:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255
    leadSource:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255
    type:
      - NotBlank: { message: 'not.blank' }
    status:
      - NotBlank: { message: 'not.blank' }
    confirmed:
      - Type: { type: "bool", message: "This value should be a boolean." }
