resources:
  App\Customer\Domain\Entity\CustomerStatus:
    paginationPartial: true
    paginationClientItemsPerPage: true
    paginationViaCursor:
      - { field: 'ulid', direction: 'DESC' }
    denormalizationContext:
      groups: ['write:customerStatus']
    operations:
      ApiPlatform\Metadata\GetCollection:
        filters:
          [
            'customer.mongodb.status.order',
            'customer.mongodb.status.partial_search',
            'mongodb.range',
          ]
      ApiPlatform\Metadata\Get:
      ApiPlatform\Metadata\Put:
      ApiPlatform\Metadata\Patch:
      ApiPlatform\Metadata\Delete:
      ApiPlatform\Metadata\Post:
    graphQlOperations:
      - class: ApiPlatform\Metadata\GraphQl\Query
      - class: ApiPlatform\Metadata\GraphQl\QueryCollection
        filters:
          [
            'customer.mongodb.status.order',
            'customer.mongodb.status.partial_search',
            'mongodb.range',
          ]
      - class: ApiPlatform\Metadata\GraphQl\Mutation
        name: create
      - class: ApiPlatform\Metadata\GraphQl\Mutation
        name: update
      - class: ApiPlatform\Metadata\GraphQl\Mutation
        name: delete

  App\Customer\Domain\Entity\CustomerType:
    paginationPartial: true
    paginationClientItemsPerPage: true
    paginationViaCursor:
      - { field: 'ulid', direction: 'DESC' }
    denormalizationContext:
      groups: ['write:customerType']
    operations:
      ApiPlatform\Metadata\GetCollection:
        filters:
          ['customer.mongodb.type.order', 'customer.mongodb.type.partial_search', 'mongodb.range']
      ApiPlatform\Metadata\Get:
      ApiPlatform\Metadata\Put:
      ApiPlatform\Metadata\Patch:
      ApiPlatform\Metadata\Delete:
      ApiPlatform\Metadata\Post:
    graphQlOperations:
      - class: ApiPlatform\Metadata\GraphQl\Query
      - class: ApiPlatform\Metadata\GraphQl\QueryCollection
        filters:
          ['customer.mongodb.type.order', 'customer.mongodb.type.partial_search', 'mongodb.range']
      - class: ApiPlatform\Metadata\GraphQl\Mutation
        name: create
      - class: ApiPlatform\Metadata\GraphQl\Mutation
        name: update
      - class: ApiPlatform\Metadata\GraphQl\Mutation
        name: delete

  App\Customer\Domain\Entity\Customer:
    paginationPartial: true
    paginationClientItemsPerPage: true
    paginationViaCursor:
      - { field: 'ulid', direction: 'DESC' }
    denormalizationContext:
      groups: ['write:customer']
    operations:
      ApiPlatform\Metadata\GetCollection:
        filters:
          [
            'customer.mongodb.search',
            'customer.mongodb.order',
            'customer.mongodb.date',
            'mongodb.range',
          ]
      ApiPlatform\Metadata\Get:
      ApiPlatform\Metadata\Put:
      ApiPlatform\Metadata\Patch:
      ApiPlatform\Metadata\Delete:
      ApiPlatform\Metadata\Post:
    graphQlOperations:
      - class: ApiPlatform\Metadata\GraphQl\Query
      - class: ApiPlatform\Metadata\GraphQl\QueryCollection
        filters:
          [
            'customer.mongodb.search',
            'customer.mongodb.order',
            'customer.mongodb.date',
            'mongodb.range',
          ]
      - class: ApiPlatform\Metadata\GraphQl\Mutation
        name: create
      - class: ApiPlatform\Metadata\GraphQl\Mutation
        name: update
      - class: ApiPlatform\Metadata\GraphQl\Mutation
        name: delete

  App\Internal\HealthCheck\Domain\ValueObject\HealthCheck:
    operations:
      ApiPlatform\Metadata\Get:
        uriTemplate: '/health'
        controller: 'App\Internal\HealthCheck\Application\Controller\HealthCheckController'
        openapi:
          responses:
            '204':
              description: 'Health check passed with no content to return.'
            '500':
              description: 'Health check failed.'
