resources:
  App\Customer\Domain\Entity\CustomerStatus:
    operations:
      ApiPlatform\Metadata\Post:
        openapi:
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    value:
                      type: string
                      example: 'Prospect'

  App\Customer\Domain\Entity\Customer:
    normalizationContext:
      groups: [ 'output' ]
    operations:
      ApiPlatform\Metadata\GetCollection:
        paginationClientItemsPerPage: true
      ApiPlatform\Metadata\Put:
        input: 'App\Customer\Application\DTO\CustomerPutDto'
        processor: 'App\Customer\Application\Processor\PutCustomerProcessor'
      ApiPlatform\Metadata\Delete:
        processor: 'App\Customer\Application\Processor\Delete'
      create_http:
        class: 'ApiPlatform\Metadata\Post'
        input: 'App\Customer\Application\DTO\CustomerCreateDto'
        processor: 'App\Customer\Application\Processor\CreateCustomerProcessor'

  App\Internal\HealthCheck\Domain\ValueObject\HealthCheck:
    operations:
      ApiPlatform\Metadata\Get:
        uriTemplate: '/health'
        controller: 'App\Internal\HealthCheck\Application\Controller\HealthCheckController'
        openapi:
          responses:
            '204':
              description: 'Health check passed with no content to return.'
            '500':
              description: 'Health check failed.'
