resources:
  App\Customer\Domain\Entity\Customer:
    operations:
      ApiPlatform\Metadata\GetCollection: ~
      create_http:
        class: 'ApiPlatform\Metadata\Post'
        input: 'App\Customer\Application\DTO\CustomerRegisterDto'

  App\Internal\HealthCheck\Domain\ValueObject\HealthCheck:
    operations:
      ApiPlatform\Metadata\Get:
        uriTemplate: '/health'
        controller: 'App\Internal\HealthCheck\Application\Controller\HealthCheckController'
        openapi:
          responses:
            '204':
              description: 'Health check passed with no content to return.'
            '500':
              description: 'Health check failed.'
