resources:
  App\Customer\Domain\Entity\CustomerStatus:
    operations:
      ApiPlatform\Metadata\GetCollection:
        filters: ['customer_value.mongodb.value_filter']
      ApiPlatform\Metadata\Get:
      ApiPlatform\Metadata\Patch:
      ApiPlatform\Metadata\Delete:
      ApiPlatform\Metadata\Post:
        openapi:
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    value:
                      type: string
                      example: 'Active'

  App\Customer\Domain\Entity\CustomerType:
    operations:
      ApiPlatform\Metadata\GetCollection:
        filters: ['customer_value.mongodb.value_filter']
      ApiPlatform\Metadata\Get:
      ApiPlatform\Metadata\Patch:
      ApiPlatform\Metadata\Delete:
      ApiPlatform\Metadata\Post:
        openapi:
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    value:
                      type: string
                      example: 'Prospect'

  App\Customer\Domain\Entity\Customer:
    operations:
      ApiPlatform\Metadata\GetCollection:
        filters: [ 'customer.mongodb.customer_filter' ]
      ApiPlatform\Metadata\Get:
      ApiPlatform\Metadata\Patch:
      ApiPlatform\Metadata\Delete:
      ApiPlatform\Metadata\Post:
  App\Internal\HealthCheck\Domain\ValueObject\HealthCheck:
    operations:
      ApiPlatform\Metadata\Get:
        uriTemplate: '/health'
        controller: 'App\Internal\HealthCheck\Application\Controller\HealthCheckController'
        openapi:
          responses:
            '204':
              description: 'Health check passed with no content to return.'
            '500':
              description: 'Health check failed.'
