sandboxId: local

fullnameOverride: ''

images:
  php:
    repository: core-service-sandbox-php
    tag: local
    pullPolicy: IfNotPresent
  caddy:
    repository: core-service-sandbox-caddy
    tag: local
    pullPolicy: IfNotPresent
  workspace:
    repository: core-service-sandbox-workspace
    tag: local
    pullPolicy: IfNotPresent
  mongodb:
    repository: mongo
    tag: '6.0'
    pullPolicy: IfNotPresent
  redis:
    repository: redis
    tag: 8.0.0-alpine
    pullPolicy: IfNotPresent
  localstack:
    repository: localstack/localstack
    tag: 3.4.0
    pullPolicy: IfNotPresent

app:
  replicaCount: 1
  workingDir: /srv/app
  service:
    type: ClusterIP
    port: 80
  env:
    appEnv: dev
    appDebug: '1'
    appSecret: sandbox-secret
    dbUser: root
    dbPassword: secret
    dbPort: 27017
    dbName: app
    dbAuthDatabase: admin
    redisDatabase: 0
    awsSqsVersion: latest
    awsSqsRegion: us-east-1
    awsSqsKey: fake
    awsSqsSecret: fake
    localstackPort: 4566
    domainEventsQueueName: domain-events
    failedDomainEventsQueueName: failed-domain-events
    serverName: caddy
    caddyMercureJwtSecret: '!ChangeThisMercureHubJWTSecretKey!'
    awsEmfNamespace: CCore/BusinessMetrics
    extra: {}
  workspace:
    gitAuthorName: vilnacrm ai bot
    gitAuthorEmail: info@vilnacrm.com
    repoDir: /workspace/core-service
    repoSubPath: repo

mongodb:
  service:
    port: 27017

redis:
  service:
    port: 6379

localstack:
  service:
    port: 4566
  services: sqs
  debug: '0'

probes:
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 12
