apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core-service-sandbox.fullname" . }}-caddy
  labels:
    {{- include "core-service-sandbox.componentLabels" (dict "root" . "component" "app") | nindent 4 }}
data:
  Caddyfile: |
    {
        auto_https disable_redirects
    }

    :80 {
        root * /srv/app/public
        encode zstd gzip
        php_fastcgi unix//var/run/php/php-fpm.sock
        file_server
        log
    }
