name: E2E testing

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  behat:
    name: Behat
    runs-on: ubuntu-latest

    steps:
      - name: Dependabot skip
        if: startsWith(github.actor, 'dependabot')
        run: echo "Skipping E2E tests for Dependabot PR"

      - name: Checkout Repository
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: Start Application
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        run: make start

      - name: Run Behat Tests
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        run: make behat

      - name: Stop application
        if: ${{ !startsWith(github.actor, 'dependabot') && always() }}
        run: make down
