name: GraphQL spec backward comparability

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write
  checks: write
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  graphql-diff:
    name: Openapi-diff
    runs-on: ubuntu-latest

    steps:
      - name: Dependabot skip
        if: startsWith(github.actor, 'dependabot')
        run: echo "Skipping GraphQL diff for Dependabot PR"

      - name: Generate token with necessary permissions
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        id: generate_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1
        with:
          app-id: ${{ secrets.VILNACRM_APP_ID }}
          private-key: ${{ secrets.VILNACRM_APP_PRIVATE_KEY }}

      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        with:
          php-version: ${{ vars.PHP_VERSION }}

      - name: Checkout Repository
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          token: ${{ !startsWith(github.actor, 'dependabot') && steps.generate_token.outputs.token || github.token }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Install Dependencies
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Start application
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        run: make start

      - name: Generate GraphQL spec
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        run: make generate-graphql-spec

      - name: Copy openapi spec to host
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        run: docker cp core-service-php-1:/srv/app/.github/graphql-spec/spec .github/graphql-spec/spec

      - name: Commit changes
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5
        with:
          add: '.github/graphql-spec/spec'
          message: 'feat(#${{ github.event.number }}): generate graphql spec'

      - name: GraphQL Inspector
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        uses: kamilkisiela/graphql-inspector@91cefc9d934ccac1b4be9f26f44b6f533c300247
        with:
          schema: '${{ github.base_ref }}:.github/graphql-spec/spec'
        env:
          GITHUB_TOKEN: ${{ !startsWith(github.actor, 'dependabot') && steps.generate_token.outputs.token || github.token }}
