name: GraphQL spec backward comparability

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write
  checks: write
  statuses: write

jobs:
  graphql-diff:
    name: Openapi-diff
    runs-on: ubuntu-latest

    steps:
      - name: Generate token with necessary permissions
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.VILNACRM_APP_ID }}
          private_key: ${{ secrets.VILNACRM_APP_PRIVATE_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v4.2.1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Start application
        run: make start

      - name: Generate GraphQL spec
        run: make generate-graphql-spec

      - name: Stop application
        if: always()
        run: make down

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '.github/graphql-spec/spec'
          message: 'feat(#${{ github.event.number }}): generate graphql spec'

      - name: GraphQL Inspector
        uses: kamilkisiela/graphql-inspector@91cefc9d934ccac1b4be9f26f44b6f533c300247
        with:
          schema: '${{ github.base_ref }}:.github/graphql-spec/spec'
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
