name: Mutation testing

on:
  pull_request:

jobs:
  infection:
    name: Infection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Start Application
        run: make start

      - name: Run infection
        run: make infection

      - name: Stop Application
        if: always()
        run: make down
