name: code quality

on:
  pull_request:

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    name: PHP Insights checks
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ vars.PHP_VERSION }}
      - name: Start application services
        run: make start
      - name: Run PHP Insights checks
        run: CI=1 make phpinsights
