name: code quality

on:
  pull_request:

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    name: PHP Insights checks
    steps:
      - uses: actions/checkout@v4
      - name: Start application services
        run: docker compose up --detach --wait php
      - name: Run PHP Insights using docker
        run: docker compose run --rm php php ./vendor/bin/phpinsights --no-interaction --ansi --disable-security-check
