name: checks

on:
  pull_request:

jobs:
  symfony-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Start application services
        run: make start

      - name: Composer validate
        run: make composer-validate

      - name: Check symfony requirements
        run: make check-requirements

      - name: Symfony security check
        run: make check-security

      - name: Stop application services
        if: always()
        run: make down
