name: Unit and Integration testing

on:
  pull_request:
    branches: ['main']

jobs:
  tests:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot skip
        if: startsWith(github.actor, 'dependabot')
        run: echo "Skipping PHPUnit for Dependabot PR"

      - name: Checkout Repository
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        with:
          php-version: ${{ vars.PHP_VERSION }}

      - name: Install dependencies
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        run: composer self-update && composer install --dev --no-scripts --no-progress && composer dump-autoload

      - name: Start application
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        run: make start

      - name: Execute all tests with coverage
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        run: make coverage-xml

      - name: Copy coverage report to host
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        run: docker compose cp php:/srv/app/coverage/coverage.xml /tmp/coverage.xml

      - name: Upload code coverage to Codecov
        if: ${{ !startsWith(github.actor, 'dependabot') }}
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: /tmp/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
