name: Unit and Integration testing

on:
  pull_request:
    branches: ['main']

jobs:
  tests:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot skip
        if: contains(toLower(github.actor), 'dependabot')
        run: echo "Skipping PHPUnit for Dependabot PR"

      - name: Checkout Repository
        if: ${{ !contains(toLower(github.actor), 'dependabot') }}
        uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        if: ${{ !contains(toLower(github.actor), 'dependabot') }}
        with:
          php-version: ${{ vars.PHP_VERSION }}

      - name: Install dependencies
        if: ${{ !contains(toLower(github.actor), 'dependabot') }}
        run: composer self-update && composer install --dev --no-scripts --no-progress && composer dump-autoload

      - name: Start application
        if: ${{ !contains(toLower(github.actor), 'dependabot') }}
        run: make start

      - name: Execute all tests with coverage
        if: ${{ !contains(toLower(github.actor), 'dependabot') }}
        run: make coverage-xml

      - name: Copy coverage report to host
        if: ${{ !contains(toLower(github.actor), 'dependabot') }}
        run: docker compose cp php:/srv/app/coverage/coverage.xml /tmp/coverage.xml

      - name: Upload code coverage to Codecov
        if: ${{ !contains(toLower(github.actor), 'dependabot') }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: /tmp/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
