name: Unit and Integration testing

on:
  pull_request:
    branches: ['main']

jobs:
  tests:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start application
        run: make start

      - name: Execute all tests with coverage
        run: make coverage-xml

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

      - name: Stop application
        if: always()
        run: make down
