#!/usr/bin/env bash
set -euo pipefail

workspace_root="${1:-${SANDBOX_WORKSPACE_ROOT:-/workspace/core-service}}"
agent_env_dir="${HOME}/.config/core-service"
agent_env_file="${agent_env_dir}/agent.env"
bashrc_file="${HOME}/.bashrc"
extra_env_file="${SANDBOX_AGENT_ENV_FILE:-}"

mkdir -p "${workspace_root}" "${agent_env_dir}"
touch "${bashrc_file}"

append_export_if_set() {
    local env_name="${1}"
    local target_name="${2:-${1}}"

    if [ -n "${!env_name:-}" ]; then
        printf 'export %s=%q\n' "${target_name}" "${!env_name}"
    fi
}

persist_env_file() {
    local tmp_file

    tmp_file="$(mktemp)"

    {
        printf '# Generated by ops/sandbox-poc/workspace/bootstrap-agent.sh\n'
        append_export_if_set SANDBOX_WORKSPACE_ROOT
        append_export_if_set OPENAI_API_KEY
        append_export_if_set OPENAI_BASE_URL
        append_export_if_set OPENAI_MODEL
        append_export_if_set OPENAI_ORG_ID
        append_export_if_set OPENAI_PROJECT
        append_export_if_set GH_TOKEN
        append_export_if_set GITHUB_TOKEN

        if [ -n "${GH_AUTOMATION_TOKEN:-}" ]; then
            printf 'export GH_TOKEN=%q\n' "${GH_AUTOMATION_TOKEN}"
            printf 'export GITHUB_TOKEN=%q\n' "${GH_AUTOMATION_TOKEN}"
        fi

        if [ -n "${GIT_AUTHOR_NAME:-}" ]; then
            printf 'export GIT_AUTHOR_NAME=%q\n' "${GIT_AUTHOR_NAME}"
            printf 'export GIT_COMMITTER_NAME=%q\n' "${GIT_COMMITTER_NAME:-${GIT_AUTHOR_NAME}}"
        elif [ -n "${GIT_COMMITTER_NAME:-}" ]; then
            printf 'export GIT_COMMITTER_NAME=%q\n' "${GIT_COMMITTER_NAME}"
        fi

        if [ -n "${GIT_AUTHOR_EMAIL:-}" ]; then
            printf 'export GIT_AUTHOR_EMAIL=%q\n' "${GIT_AUTHOR_EMAIL}"
            printf 'export GIT_COMMITTER_EMAIL=%q\n' "${GIT_COMMITTER_EMAIL:-${GIT_AUTHOR_EMAIL}}"
        elif [ -n "${GIT_COMMITTER_EMAIL:-}" ]; then
            printf 'export GIT_COMMITTER_EMAIL=%q\n' "${GIT_COMMITTER_EMAIL}"
        fi

        if [ -n "${extra_env_file}" ] && [ -f "${extra_env_file}" ]; then
            printf '. %q\n' "${extra_env_file}"
        fi
    } > "${tmp_file}"

    chmod 600 "${tmp_file}"
    mv "${tmp_file}" "${agent_env_file}"
}

ensure_bashrc_sources_env() {
    local start_marker end_marker tmp_file

    start_marker="# BEGIN SANDBOX AGENT ENV"
    end_marker="# END SANDBOX AGENT ENV"
    tmp_file="$(mktemp)"

    awk -v start="${start_marker}" -v end="${end_marker}" '
        $0 == start {skip=1; next}
        $0 == end {skip=0; next}
        skip == 0 {print}
    ' "${bashrc_file}" > "${tmp_file}"

    cat >> "${tmp_file}" <<'EOF'

# BEGIN SANDBOX AGENT ENV
if [ -f "$HOME/.config/core-service/agent.env" ]; then
    . "$HOME/.config/core-service/agent.env"
fi
# END SANDBOX AGENT ENV
EOF

    mv "${tmp_file}" "${bashrc_file}"
}

git config --global --add safe.directory "${workspace_root}" || true
git config --global init.defaultBranch "${GIT_DEFAULT_BRANCH:-main}" || true

if [ -n "${GIT_AUTHOR_NAME:-}" ]; then
    git config --global user.name "${GIT_AUTHOR_NAME}"
elif [ -n "${GIT_COMMITTER_NAME:-}" ]; then
    git config --global user.name "${GIT_COMMITTER_NAME}"
fi

if [ -n "${GIT_AUTHOR_EMAIL:-}" ]; then
    git config --global user.email "${GIT_AUTHOR_EMAIL}"
elif [ -n "${GIT_COMMITTER_EMAIL:-}" ]; then
    git config --global user.email "${GIT_COMMITTER_EMAIL}"
fi

persist_env_file
ensure_bashrc_sources_env

printf 'workspace_root=%s\n' "${workspace_root}"

if command -v codex >/dev/null 2>&1; then
    printf 'codex_version=%s\n' "$(codex --version)"
else
    printf 'codex_version=not-installed\n'
fi

if command -v gh >/dev/null 2>&1; then
    printf 'gh_version=%s\n' "$(gh --version | head -n 1)"
fi
